GET http://localhost:8080/api/v1/product/all
Accept: application/json

###
### Send POST request with json body
POST http://localhost:8080/api/v1/product/add
Content-Type: application/json

{
  "name": "main 1"
}

###
DELETE http://localhost:8080/api/v1/product/1
Content-Type: application/json
