POST http://localhost:8080/api/v1/tableInfo/update/status
Content-Type: application/json

{
    "name": "3",
    "status": "COOK"
}

###
GET http://localhost:8080/api/v1/tableInfo/2
Accept: application/json


###
GET http://localhost:8080/api/v1/tableInfo/all
Accept: application/json

###
POST http://localhost:80/api/item
Content-Type: application/json

{}

###

